spring:
  application:
    name: ms-events
#  datasource:
#    url: jdbc:mysql://localhost:3306/ticketreck
#    username: root
#    password: contra
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://ticketreck-db-mysql.cf4gakmqo0vw.us-east-1.rds.amazonaws.com:3306/ticketreckDB
    username: admin
    password: xWwbbN9sYkKlLJJb6jz5
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://54.211.227.50:8080/realms/ticketrek

eureka:
  instance:
    hostname: 3.87.226.2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.234.78.224:8761/eureka

server:
  port: 8083
